### ISSUE TITLE
In china always offline

### ISSUE THREAD

**Issue by CatTail** [sindresorhus/is-online#1]
Even I was online, always return offline because I was in china

**Comment by razvanilin** [comment]
Hey guys @sindresorhus @silverwind 

I am using you module in one of my applications and a client from China can't run the app properly. After some investigation I figured out that the module is causing this because it appears to be offline in China.

Has anyone actually tested if it works in China?

**Comment by SamVerschueren** [comment]
@razvanilin It seems that it should work in China though. [Here](https://github.com/sindresorhus/is-online/blob/master/hostnames.js) you can find the list of hostnames being checked. If I'm not mistaken, baidu.com is a chinese social network? So either your client is running the app on a network where baidu is being blocked, or something else is going on.

**Comment by razvanilin** [comment]
I will look more into it. It might be the case that the local firewall is blocking the application too.

**Comment by silverwind** [comment]
If it returns offline then both checks must fail. The first check is basically this:

```
$ dig @198.41.0.4 ns . | grep SERVER
;; SERVER: 198.41.0.4#53(198.41.0.4)
```
The returned address must match the queried one for the check to succeed.

The second check is a TCP connection to the mentioned domains, e.g.:
```
$ nc -v baidu.com 80
Connection to baidu.com 80 port [tcp/http] succeeded!
```

Can you try these commands?

**Comment by razvanilin** [comment]
I managed to connect remotely to my client's machine and tested these.

The second command took about 5-7 seconds to complete and also got some warnings simillar to this `Warning: inverse host lookup failed for 220.181.57.217: h_errno 11004: NO_DATA`. Could this be the reason?

I also instructed him to test the application on a different network and machine and it still didn't work.

I have clients in other parts of the world but I never got complaints about this so maybe it's a China specific issue.

**Comment by silverwind** [comment]
The failed reverse lookup is probably harmless. If a simple TCP connection takes 7 seconds, I think either their network is heavily congested or China's firewall is doing a ton of checks.

I'd be open to adding a faster domain for chinese users if it helps, and I think we should make the timeout configurable for your case.

**Comment by silverwind** [comment]
Also see https://github.com/sindresorhus/is-online/pull/28

**Comment by razvanilin** [comment]
I'll hard-code the values in the module myself to make another test build. I will let you know if that fixes the problem for China.

**Comment by razvanilin** [comment]
So I put a 3 seconds timeout and it still didn't fix their issue. I ended up overwriting the isOnline function with my own settings which bypasses the check in certain situations.
