### ISSUE TITLE
iojs / node 0.12: dns.setServers

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/is-online#12]
Looks like we can drop the `native-dns` dependency sometimes in the future with this:

https://iojs.org/api/dns.html#dns_dns_setservers_servers

**Comment by sindresorhus** [comment]
For now we can use that when available and fall back to `native-dns`.

**Comment by silverwind** [comment]
Right, will do some feature-detection for it. Will be worth it considering the remaining bugs in that module.

**Comment by silverwind** [comment]
Now with node 0.12 out, how do you feel about removing the `native-dns` dependency and pushing a new major version which requires 0.12/io.js?

It'd shorten the code considerably, with the only downside being that the core dns library doesn't make the source of the answer packet available, but I think that's acceptable).

**Comment by sindresorhus** [comment]
:+1:

**Comment by silverwind** [comment]
As noted in the PR, the core API isn't enough to keep the same functionality, so I don't think it's worth doing this at all.
