### ISSUE TITLE
onetime called multiple times

### ISSUE THREAD

**Issue by AscaL** [sindresorhus/is-online#16]
In index.js from line 56, on connect ``` cb(null, true)``` is called, the socket is closed and next is called with an error, which leads (if i understood it correctly) to the call of ```cb(null, false)```.
Since in line 17 ```cb = onetime(cb)``` is called we get two calls of onetime which leads to an error.

``` javascript 
socket.connect(80, domain, function () {
					cb(null, true);
					socket.end();
					next(new Error()); // skip to end
				});
			}, function () {
				cb(null, false);
			});
```

**Comment by kevva** [comment]
ping @silverwind

**Comment by silverwind** [comment]
I don't think it's possible to run `cb` twice. The second call should end [here](https://github.com/sindresorhus/onetime/blob/b514921e272a593e88d195d976dfab22f18e2ad7/index.js#L12-L19) (it won't throw as we aren't using that option), and on a successful connect, `cb(null, false)` should practically be a noop.

**Comment by AscaL** [comment]
I get what you mean, you are right it should not go there, it is very very strange but this is what happened to me on windows 8.1 (it worked fine on mac/linux as far as i know) in case you want to take a look: 

![image](https://cloud.githubusercontent.com/assets/8880943/6690220/7fbc7f2c-ccbf-11e4-803a-c8c1d36789eb.png)

**Comment by silverwind** [comment]
I can't really explain that. We're not giving `errMsg` to onetime, so it really shouldn't throw. @kevva any idea?

**Comment by sindresorhus** [comment]
@AscaL Which version of `is-online` and `onetime` is used there? (check their package.json)

**Comment by AscaL** [comment]
I'm not able to check on that machine right now but the line i have in the repo's package.json is
``` "is-online": "^3.1.0" ```

**Comment by kevva** [comment]
Looks like it's coming from this line https://github.com/sindresorhus/is-online/blob/master/index.js#L54.

**Comment by silverwind** [comment]
Looks light there *might* be some misuse of `eachAsync` in there, as `next` is really a `done`. Still can't explain the throwing though.

**Comment by sindresorhus** [comment]
So my current theory is that both https://github.com/sindresorhus/is-online/blob/c3b69be82d2f3d6787291728472e856a8da9e9c7/index.js#L59 and gets called https://github.com/sindresorhus/is-online/blob/c3b69be82d2f3d6787291728472e856a8da9e9c7/index.js#L54 which throws as that's how `each-async` uses `onetime`.

**Comment by silverwind** [comment]
It certainly is possible that the socket connects suceeds, but immediatly errors before the `connect` callback is called.

**Comment by silverwind** [comment]
I think I'd just remove the `next` on L54, it's unnecessary. Do we still need the error argument on L59? I never quite understood why its used.

**Comment by kevva** [comment]
Because it should stop after successfully connecting to one of the domains.

**Comment by silverwind** [comment]
Ah, right. It stops the iteration. I'll push a fix.

**Comment by silverwind** [comment]
@AscaL pushed 3.1.1, let me know if that works.

**Comment by AscaL** [comment]
Will let you know as soon as i can. Thanks!

**Comment by silverwind** [comment]
I think while the change might fix @AscaL's case, not calling the iteration callback on error could lead to `eachAsync` never finishing on errors. I'll have to reconsider that fix.

**Comment by silverwind** [comment]
I'm sorry, I shot too fast on that patch and had to revert it. We have to think of something else. The error @AscaL is getting must somehow come from eachAsync's onetime, but the stack points to this module.

**Comment by silverwind** [comment]
@AscaL could you post the output of `npm ls` inside your project folder?

**Comment by silverwind** [comment]
Minimal testcase of the issue:

````js
'use strict';

var eachAsync = require('each-async');
var onetime = require('onetime');

module.exports = function (cb) {
	cb = onetime(cb);
	eachAsync([1,2,3], function (value, i, done) {
		done();
		cb(null, true);
		done(new Error()); // skip to end
	}, function () {
		cb(null, false);
	});
};
````

````
$ node -pe 'require("./try.js")(console.log)'
undefined
null true
C:\git\is-online\node_modules\onetime\index.js:15
                                throw new Error(fnName + ' can only be called once.');
                                      ^
Error: callback() can only be called once.
    at C:\git\is-online\node_modules\onetime\index.js:15:11
    at Immediate.<anonymous> (C:\git\is-online\try.js:11:3)
    at Immediate.immediate._onImmediate (timers.js:431:18)
    at processImmediate [as _immediateCallback] (timers.js:369:17)
````

**Comment by sindresorhus** [comment]
Yes, I was going to suggest that.

**Comment by AscaL** [comment]
Just an update: I stopped getting the error.
Thanks!

**Comment by kevva** [comment]
Sweet!
