### ISSUE TITLE
Object has no method 'equals' - is-online@4.0.0

### ISSUE THREAD

**Issue by przemyslawpluta** [sindresorhus/is-online#17]
Running default example produces error msg:

```js
var isOnline = require('is-online');

isOnline(function(err, online) {
    console.log(online);
    //=> true
});
```

```bash
/tag/node_modules/is-online/index.js:38
		if (msg.slice(0, 2).equals(transactionID) && rinfo.address === server) {
		                    ^
TypeError: Object �� has no method 'equals'
    at Socket.<anonymous> (/tag/node_modules/is-online/index.js:38:23)
    at Socket.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:440:8)
```

**Comment by sindresorhus** [comment]
What node version are you on? `$ node --version`

**Comment by silverwind** [comment]
Right, Buffer.equals is a 0.12 API, but I think we can do in a 0.10.x compatible way.

**Comment by sindresorhus** [comment]
@silverwind Weird, why did the tests pass on 0.10 then? https://travis-ci.org/sindresorhus/is-online/jobs/60281538

**Comment by silverwind** [comment]
Hmm something about the test engine? I can see that the callback to `isOnline` in `test.js` never executes. It almost seems as it return synchronous, is that possible?

**Comment by sindresorhus** [comment]
@silverwind Yeah, seems like a bug there. I've worked around it for now. https://github.com/sindresorhus/is-online/commit/8f51f30bcca6a31f6da61a41a80baba6c62ce5a3

**Comment by silverwind** [comment]
Yep, that works. I'll push a patch shortly.
