### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/is-online#19]
@silverwind I was planning to do a release. Would you mind looking through the changes and :+1: ?

https://github.com/sindresorhus/is-online/compare/v4.0.2...master

**Comment by silverwind** [comment]
@sindresorhus looking good. I just pushed another small tweak which may help with certain proxies. Release at will. :+1:

**Comment by sindresorhus** [comment]
Thanks for the review and your changes looks good. 5.0.0 released ;)

**Comment by sindresorhus** [comment]
Sidenote: I wonder if this could be abstracted into a `dns-query` module or something https://github.com/sindresorhus/is-online/blob/0877cd64b20fb5b4593e9441e60fd6e3b085b727/index.js#L17-L28

**Comment by silverwind** [comment]
It probably could, but I don't see much reusabilty in the current form. If we add the ability to parse A and AAAA records from the answer packet, I could see it being useful as a minimalistic dns resolver alternative to core's c-ares (Which is hopefully soon to change - https://github.com/nodejs/io.js/pull/1843).

**Comment by sindresorhus** [comment]
Yeah. Was just a thought. I'm not going make it, but happy to depend on future a module you make for it ;)
