### ISSUE TITLE
A better way to detect dns intercepting 

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/is-online#22]
DNS version queries might be a even better way to detect routers which intercept DNS, even when they respond with the source IP of the queried nameserver. If we send a query for `version.bind` with class `CHAOS` and type `TXT`, most DNS servers respond with a certain string (which is not specific to `bind`, despite its name):

```
$ dig +short @ns3.cloudmark.com version.bind chaos txt
"none"
```

With DNS intercepting in place, the query ought to return either a different string or an error like `NOTIMP` / `SERVFAIL` (seen on `ns1.google.com`/`8.8.8.8`) status codes. Here's an example:

```
 $ dig +short @ns3.cloudmark.com version.bind chaos txt
"dnsmasq-2.73"
```

What we need is a IP address of a nameserver that is guaranteed to always return a certain string we can test for. Unfortunately, the root servers are not suitable as they apparently return a wide range of different strings which ought to get changed at some point. The best candidate seems to be the `c` root which sports a static versionless string:

```
$ dig +short @c.root-servers.net version.bind chaos txt
"c-root"
```

Can anyone think of other suitable nameserver?

**Comment by sindresorhus** [comment]
Can't think of any other. Maybe we should just try using the `c` root and see how it fares?

**Comment by silverwind** [comment]
I'll think about something. The servers hosting the `io` zone also look suitable, but of course there's no guarantees that this is static:

```
$ dig +short @ns-a3.io version.bind chaos txt
"this page intentionally left blank"
```

**Comment by sindresorhus** [comment]
I just thought of a possibly simpler solution, how about we use the same captive portal detection as used in macOS/iOS and try to fetch http://captive.apple.com/hotspot-detect.html and ensure the HTML body/title is `Success`?

**Comment by silverwind** [comment]
Interesting. A check where we can actually verify the response body could replace all our domain test.

**Comment by sindresorhus** [comment]
@silverwind Some companies could have blocked it though, so would still be nice with some fallbacks, but we could try that first.

**Comment by silverwind** [comment]
I think it should be mostly fine without fallbacks, but if we have more simple sites where we can verify the response, we could add those as fallbacks. https://icanhazip.com/ comes to mind too for such a check, and the [author](https://major.io/icanhazip-com-faq/) seems to be fine with it, I guess:

> **Can I add checks against these domains to my scripts?**
> Sure! Just try not to smash the service with unneeded requests.

**Comment by sindresorhus** [comment]
Sounds good

**Comment by silverwind** [comment]
I think I have an even better idea: We extend `public-ip` to support an optional `https` option which goes to `ipv{4,6}.icanhazip.com` instead of DNS. 

For `is-online`, we then launch the v4 and v6 dns versions of `public-ip` in parallel, and if both fail, we fallback to the http versions. The big benefit is that we can verify the response in all tests and a https check is pretty much tamper-proof in itself.

**Comment by sindresorhus** [comment]
👍
