### ISSUE TITLE
5.1.0 is broken on node

### ISSUE THREAD

**Issue by leanderlee** [sindresorhus/is-online#23]
Running `npm install is-online` (installs 5.1.0)

and then running:
```js
var isOnline = require('is-online');

isOnline(function(err, online) {
    console.log(online);
    //=> true
});
```
As per the example -- doesn't work.

If you run `npm install is-online@5.0.1` it works fine.

**Comment by leanderlee** [comment]
I'm using node v4.3.1

**Comment by sindresorhus** [comment]
Ugh, probably npm that broke something during publish... That's known to happen.

I did a new patch release. Should be good now.
