### ISSUE TITLE
I'm getting 'undefined'

### ISSUE THREAD

**Issue by Artem-Schander** [sindresorhus/is-online#25]
I have a electron app where I'm trying to check if a connection is availible. I've done it like in your readme but the console logs always `undefined`.
I have also tried your `is-reachable` with the google example, but same result.

**Comment by SamVerschueren** [comment]
Are you sure you check the correct parameter in the callback? The first is most likely the error (which will be undefined).

**Comment by Artem-Schander** [comment]
yep, I'm sure.
Here is my code:

    isReachable('google.com:80', (err, reachable) => {
        console.log(reachable);
    });

or

    isOnline(function(err, online) {
        console.log(online);
    });

**Comment by SamVerschueren** [comment]
And what does err return?

From the docs
> Same as above except the callback doesn't have an error parameter.

Not sure if err is undefined or the first param actually is the result.

**Comment by Artem-Schander** [comment]
I've also tried the following while connected / disconnected:

    isOnline(function(online) {
        console.log(online);
    });

Both results were `false`

**Comment by Artem-Schander** [comment]
BTW. I'm including it via `import isOnline from 'is-online';` and compile it then with babel.
But that should be not the reason for this issue. I hope.

All the other ES6 stuff works well.

**Comment by silverwind** [comment]
Neither `is-online` nor `is-reachable` are capable of returning `undefined` to the callback. Try this in the REPL (the `null true` are the callback args in this case):

```js
$ node
> require('is-reachable')('sindresorhus.com', console.log)
undefined
> null true
```

**Comment by Artem-Schander** [comment]
@silverwind 
`GET file://google.com/favicon.ico?1457219323579 net::ERR_FILE_NOT_FOUND`

maybe it's because of `electron` ?

**Comment by silverwind** [comment]
You're getting the browser API: https://github.com/sindresorhus/is-reachable/blob/master/browser.js

As to why, I'm not sure, I thought electron scripts should get the node version?

**Comment by jdrew1303** [comment]
Hey I ran into the same issue. It may be because there is no `main` property set in the `package.json`. Also if you're using browserify or webpack they will fallback to browser instead. Great little lib though. 😃

**Comment by sindresorhus** [comment]
> It may be because there is no main property set in the package.json. 

Proof? Electron handles no "main" just fine, which is optional btw.

**Comment by jdrew1303** [comment]
@sindresorhus I experienced a similar issue and at the time was investigating that avenue. It was a maybe rather than a definite. 

The actual issue is that the documentation is wrong on the signature of the function. 

The first item is the online status and not an error. Thats why they're getting undefined. 

isOnline((online) => {
  $scope.isOnline = online;
});

should work as expected.

**Comment by silverwind** [comment]
I'd say the documentation is right. Both `is-online` and `is-reachable` have:

> # Browser API
> Same as above except the callback doesn't have an error parameter.

**Comment by silverwind** [comment]
The issue here is still, that electron should never get `browser.js` in first place. Maybe someone affected can test if adding `main` resolves this.

**Comment by Artem-Schander** [comment]
in fact electron runs two processes
1. `main` process (node server)
2. `renderer` (chromium browser / client)

so (it is how it should be) if you run it from the `renderer` it's the browser api.
