### ISSUE TITLE
Timeout of 1000ms seems too low

### ISSUE THREAD

**Issue by satazor** [sindresorhus/is-online#26]
I get intermittent `false` from `isOnline` even though I'm online through my WIFI. 

After debugging, the culprit was the global timeout of 1000ms which seems kind of low, especially for unreliable connections such as wireless ones. Perhaps make this higher or customizable?

**Comment by sindresorhus** [comment]
More than 1s for a tiny UDP packet is very slow. Probably a lot of interference causing high packet loss.

Not really interested in an option, but I guess we could increase it to 2s. @silverwind Thoughts?

**Comment by satazor** [comment]
The distance from where I was testing was quite large, but I can still use my internet without much problems.

**Comment by silverwind** [comment]
No objection from my side to making it 2s.
