### ISSUE TITLE
Return promises

### ISSUE THREAD

**Issue by ao95** [sindresorhus/is-online#27]
Since we have access to most ES6 features nowadays, would it be possible to return a promise instead of callback?

Will have a look at the code soon and check if it's anything I could do as a PR.

**Comment by SamVerschueren** [comment]
Off course. Sindre switched most of his modules to promises but we missed some. PR more then welcome.

**Comment by sindresorhus** [comment]
PR welcome :)

**Comment by onury** [comment]
I've implemented this. Has support for both callbacks and promises.
Updated tests, readme, etc.. See [fork here](https://github.com/onury/is-online).

Before I send a PR, should I bump minor or major version?

**Comment by SamVerschueren** [comment]
No don't bump and just drop callback support, we're not interested in supporting both.

**Comment by onury** [comment]
Promises are supported only if env has `Promise`.  So without callbacks, it will not work in non-promise environments. If you're looking for built-in Promise support; I don't have the time.

**Comment by SamVerschueren** [comment]
Just use `pinkie-promise` which is a `Promise` ponyfill. If promises are supported, it will use the built-in one, if not it will use a polyfill.

**Comment by ao95** [comment]
Sorry about not getting back on this, got my schedule filled.  
Nice work @onury

**Comment by sindresorhus** [comment]
Would simplify the code here a bit if someone did https://github.com/sindresorhus/is-reachable/issues/8 first.

**Comment by xnramx** [comment]
I've replaced the callback with a promise, although if the pull request is accepted it's necessary to increase the major version of the library.
