### ISSUE TITLE
Fails to properly detect "online" under OS X 10.12 (aka macOS Sierra)

### ISSUE THREAD

**Issue by brendandixon** [sindresorhus/is-online#29]
"pings" to all of the hosts in hostname.js work fine as does full browsing. Yet, this module returns "false" when running under OS X 10.12 (aka macOS Sierra).

**Comment by silverwind** [comment]
A working ICMP doesn't really tell you much. Try actually connecting to a port, e.g. `nc -v hostname 80`.

**Comment by brendandixon** [comment]
@silverwind Those all work. I should have mentioned that browsing is fine.

The problem, I now believe, occurs because I'm running within a corporate network. I've not had the time to determine what's not working, but an assumption made, likely by is-reachable, is too restrictive for many networks.

**Comment by silverwind** [comment]
`is-reachable` does not work reliably behind a forced proxy (Browsers generally do). It's one of the harder problems to solve because of the many mechanisms through which a system can obtain such a proxy. Is my assumption correct that when turn off the proxy, you can't reach the internet?

**Comment by brendandixon** [comment]
@silverwind If the browser runs with a proxy, it is set automatically (browsers allow this) and I have no control, and so cannot test. But I suspect that is the issue.

**Comment by silverwind** [comment]
You can possibly detect a system proxy with `networksetup -getwebproxy "Ethernet"`. Also I found this node module which looks promising: https://github.com/sholladay/os-proxy

**Comment by blahah** [comment]
I don't think this is to do with corporate networks or proxies. I am using macOS 10.12, connecting over Wi-Fi with no proxy and can browse fine, make p2p connections, etc. but `is-online` always gives `false`.
