### ISSUE TITLE
DoD root server timing out

### ISSUE THREAD

**Issue by scotttrinh** [sindresorhus/is-online#30]
Not sure if there is anything to do about this, but I'm getting false negatives because the Department of Defense root server always times out. Not sure if this is unique to my location or network setup, but I thought it was worth mentioning. Maybe add an option to specify the root server for more consistency?

[Traceroute output](http://network-tools.com/default.asp?prog=trace&host=g.root-servers.net)

```
192.112.36.4 is from United States (US) in region North America
Input: g.root-servers.net
canonical name: g.root-servers.net
Registered Domain: root-servers.net

TraceRoute from Network-Tools.com to 192.112.36.4 [g.root-servers.net]
Hop (ms)    (ms)    (ms)             IP Address Host name
1     0       0       0          206.123.64.217   -  
2     0       0       0          64.124.196.225  xe-4-2-0.er2.dfw2.us.above.net  
3     1       1       1          64.125.13.210    -  
4     6       6       6          67.14.13.218    iah-edge-18.inet.qwest.net  
5     10      10      10         63.158.243.46   63-158-243-46.dia.static.qwest.net  
6     Timed out       Timed out       Timed out               -  
7     Timed out       Timed out       Timed out               -  
8     Timed out       Timed out       Timed out               -  
9     Timed out       Timed out       Timed out               -  
10    Timed out       Timed out       Timed out               -  
11    Timed out       Timed out       Timed out               -  
12    Timed out       Timed out       Timed out               -  
13    Timed out       Timed out       Timed out               -  
14    Timed out       Timed out       Timed out               -  
15    Timed out       Timed out       Timed out               -  
16    Timed out       Timed out       Timed out               -  
17    Timed out       Timed out       Timed out               -  
18    Timed out       Timed out       Timed out               -  
19    Timed out       Timed out       Timed out               -  
Trace aborted.
```

**Comment by silverwind** [comment]
How did you conclude that it's this particualar server? The traceroute doesn't really tell anything, except that a firewall on the way is dropping traceroute probes.

I imagine DoD's servers might not be as geographically distributed as others. We could possibly query two random servers in parallel to account for single outages.

**Comment by scotttrinh** [comment]
Honestly, I just did a ping on each server to see if I got through, and they all worked except g. I like the idea of checking two servers: seems like a good, robust solution. Would you like a PR for that?

**Comment by silverwind** [comment]
👍 to a PR for that.

A better test than ping would be something like this, by the way:

```
dig +time=2 @192.112.36.4 . ns &>/dev/null && echo "reachable" || echo "unreachable"
```

**Comment by scotttrinh** [comment]
Thanks for that! My unix-fu is not great. :) I'll put in a PR for parallel testing.

**Comment by scotttrinh** [comment]
Thanks @silverwind and @sindresorhus for the rewrite! 🎉 😻
