### ISSUE TITLE
dgram.js error after upgrading to version 6.0.0

### ISSUE THREAD

**Issue by sylvainbaronnet** [sindresorhus/is-online#34]
Node version : `v6.9.1` (tried `v6.9.2` too)

Doing : 
```
isOnline().then(online => {
    // ...
  })
```

```
dgram.js:530
    throw new Error('Not running'); // error message from dgram_legacy.js
    ^

Error: Not running
    at Socket._healthCheck (dgram.js:530:11)
    at Socket.close (dgram.js:424:8)
    at Timeout.setTimeout (/Users/sylvain/git/gd-cli/node_modules/is-online/index.js:48:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by sylvainbaronnet** [comment]
if I comment : 
`// udpSocket.close();`

It works correctly. Maybe it's not required to close since it timeout ?

**Comment by xnramx** [comment]
probably is necessary add another validation:

`if (udpSocket && udpSocket.Socket) {`

Can you check ?

**Comment by silverwind** [comment]
The issue looks to be that the `udpSocket` variable is not shared correctly between the two functions. The `udpSocket = null` in `listen` does only change the local variable on that function's scope, not the one in `send`. I'll fix that by using a top-scope variable.
