### ISSUE TITLE
verison ^6.0.0 doesnt seem to resolve the promise it gives

### ISSUE THREAD

**Issue by crostine** [sindresorhus/is-online#36]
i noticed my code broke after updating to 6.0.0, turns out 5.2.0 works fine,
6.0.0 and newer never resolve the promise it now throws "Error: Not running"

```
# node
> let i = require( './' )
undefined
> i( {}, function(err,status){
... console.log( err, status )
... })
Promise { <pending> }
> Error: Not running
    at Socket._healthCheck (dgram.js:527:11)
    at Socket.close (dgram.js:421:8)
    at Timeout.setTimeout [as _onTimeout] (C:\Software\Clerk Systems\updater\node_modules\is-online\index.js:48:15)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
>
```

**Comment by silverwind** [comment]
This sound similar to https://github.com/sindresorhus/is-online/issues/34 which was fixed in 6.0.1, are you updated?

**Comment by silverwind** [comment]
Oh, and by the way, the callback you specified does nothing, correct usage would be:

```
> require(".")({}).then(console.log)
Promise { <pending> }
> true
```

**Comment by crostine** [comment]
hm so the api of this module changed without any backward compatibility?

turns out 6.0.1 does work if used properly ...

ill change my code >.>

**Comment by silverwind** [comment]
> hm so the api of this module changed without any backward compatibility?

Yes, that happened in 6.0. You should always check what's changed before updating a major version.
