### ISSUE TITLE
In Electron, it is not working

### ISSUE THREAD

**Issue by Dhyey** [sindresorhus/is-online#37]
In electron, I am getting 404 becuase url it makes is: 

GET file://www.google.com/favicon.ico?1484028202894 net::ERR_FILE_NOT_FOUND
GET file://www.cloudflare.com/favicon.ico?1484028202894 net::ERR_FILE_NOT_FOUND
GET file://www.baidu.com/favicon.ico?1484028202894 net::ERR_FILE_NOT_FOUND
GET file://www.yandex.ru/favicon.ico?1484028202894 net::ERR_FILE_NOT_FOUND

**Comment by sindresorhus** [comment]
@silverwind Why are we not prefixing the hostnames with `https://`?

**Comment by silverwind** [comment]
Because protocol is set in `is.reachable`: https://github.com/sindresorhus/is-reachable/blob/3c1970d05810c1ac6493fdcfb17065003adfb9a8/index.js#L13-L15.

**Comment by sindresorhus** [comment]
I guess the problem is that we use a protocol-relative URL here: https://github.com/sindresorhus/is-reachable/blob/3c1970d05810c1ac6493fdcfb17065003adfb9a8/browser.js#L14 Maybe we should just use `https://` there? See: https://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by silverwind** [comment]
Yes, makes sense. Didn't know that electron resolves `//` to `file://`.
