### ISSUE TITLE
Setting different hostnames

### ISSUE THREAD

**Issue by jplethier** [sindresorhus/is-online#38]
I am trying to pass hostnames to isOnline(), using `isOnline({hostnames: ["http://www.google.com"]})`, but it is always using the hostnames listed on hostnames.js file, ignoring the hostnames I passed when call `isOnline()`

I am using it on electron too, so I need to pass hostnames as options to be able to use `http` or `https` on requests that check internet, because without this the lib automatically does the requests using `file://`

**Comment by silverwind** [comment]
Addressed URL support in https://github.com/sindresorhus/is-reachable/commit/aa425c29178b663e44e249c40621440a2390fa01.

**Comment by jplethier** [comment]
@silverwind can you estimate when this changes will be released?

**Comment by silverwind** [comment]
Right now we're contemplating removing the `is-reachable` dependency entirely (https://github.com/sindresorhus/is-online/issues/22#issuecomment-276912618). Is there any specific reason why you can't use `is-reachable` directly?

**Comment by jplethier** [comment]
no, I am already thinking about this, to use `is-reachable` directly. But you will remove and `is-online` will work in a different way of `is-reachable`?

**Comment by silverwind** [comment]
Yes, after the removal, there would only be the root dns and the predefined URL check (which arguably could be made configurable).

`is-online` is all about checking if you have a working internet connection.
`is-reachable` is about checking if you can reach a particular server.

**Comment by jplethier** [comment]
With this, it is more interesting to me to keep using `is-online`. Because check the internet is exactly what I need. The only reason why I need to be able to configure the url to check is because I am using this on an electron app, and on electron when I check an url without `http` it tries to check with `file://`

**Comment by silverwind** [comment]
Isn't there a way to force electron to load the Node.js version of this module? . E.g. not use the `browser` field from package.json, but instead use `main` (which defaults to `index.js`).

Anyways, I'll get to releasing.

**Comment by silverwind** [comment]
Released `6.1.0` which supports URLs for the `hostnames`.

**Comment by jplethier** [comment]
Thank you @silverwind, and thanks for the quick replies
