### ISSUE TITLE
Watch when is online or offline

### ISSUE THREAD

**Issue by iamazik** [sindresorhus/is-online#41]
Is there a watcher that I can use when the connection is down or up? I thought it would be good to ask you before implementing the `setTimeout()` to manually send request on every second.

**Comment by silverwind** [comment]
Polling this module is certainly not the right approach, and I'd wager your IP will get blocked sooner or later if you start polling every second, because that's just a waste of resources.

A low-overhead method might be to set up a Web Socket and transfer ping frames regularily, but I suggest you handle network error conditions as they arise when you transfer application data.

**Comment by iamazik** [comment]
Thank you @silverwind . You got my point and that's why I don't want to use the `setTimeout()`. Do you got any doc or resource like about the Web socket and transfer ping that I can take a look to get some ideas?

**Comment by silverwind** [comment]
No real example, but for Node.js, you could use https://github.com/websockets/ws for example and use the ping/pong methods and events, but that will take a bit of a setup.

**Comment by sindresorhus** [comment]
In the browser you could subscribe to do the following events and run this module then:

```js
window.addEventListener('offline', () => {});
window.addEventListener('online', () => {});
```

**Comment by iamazik** [comment]
Thanks @silverwind . This is very clever. So, I came up with the following solution:

```javascript
window.addEventListener('offline', () => {
  isOnline({timeout: 1000}).then(online => {
    if (!online) {
      this.online = false
    }
  })
})

window.addEventListener('online', () => {
  isOnline({timeout: 1000}).then(online => {
    if (online) {
      this.online = true
    }
  })
})
isOnline({timeout: 1000}).then(online => {
  if (!online) {
    this.online = false
  }
})
```

The `isOnline()` method on the last part was used because once the Electron app starts and if there is no Lan or Wifi connection, the `window. addEventListener('offline')` doesn't fire. I added the event under the Vue `mounted()` method. So, I had to use the `isOnline()` method again outside of the `window.addEventListener()` event.

**Comment by marufmax** [comment]
`window.addEventListener('offline')` will use browser's `navigator.onLine` under the hood. Which is useless because it only detect if LAN connection is available or not. If you have multiple connection for VMs then this will not work.
