### ISSUE TITLE
Incompatibility with create-react-app

### ISSUE THREAD

**Issue by adam187** [sindresorhus/is-online#42]
This is followup to PR  https://github.com/sindresorhus/ip-regex/pull/12 

`sindresorhus/ip-regex` is in dependency chain of this package
`sindresorhus/public-ip` > `sindresorhus/is-ip`  > `sindresorhus/ip-regex`

In PR you wrote that this `sindresorhus/ip-regex` is targeted for node (which i totally understand) and same probably goes for `sindresorhus/is-ip`, but this package and `sindresorhus/public-ip` are targeted also for browser. 

Right now you can't use this package or `sindresorhus/public-ip` in scenario with `webpack` + `uglifyjs` without explicitly setting up babel for this modules or using `babel-engine-plugin` like you suggested in PR. 

Problem is when you have React app build using https://github.com/facebookincubator/create-react-app
where by default you can't change `webpack` without [ejecting](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-eject) whole configuration. 

More details [here](
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

Ejecting while configuration only to use one module is a bit overkill in my opinion. 

So my question is do you have any other idea how this module could be useable with `react-scripts` without making this package (and packages in dependency chain) published with `es2015` versions ?

Or could you at least improve README with info that it requires `babel-engine-plugin` to work with `uglifyjs@2`?

**Comment by sindresorhus** [comment]
This is a shortcoming of `create-react-app` and should be resolved there. Everyone always just wants to solve their own immediate problem quickly instead of thinking bigger and solving the underlying problem. I'm not going to change anything for `webpack` or `create-react-app`, sorry.

See https://github.com/sindresorhus/ama/issues/446 and https://github.com/facebookincubator/create-react-app/issues/1125.
