### ISSUE TITLE
Heroku complain npm run build fails to minify

### ISSUE THREAD

**Issue by debotos** [sindresorhus/is-online#44]
Please compile the code to ES5

**Comment by SamVerschueren** [comment]
We aim for Node.js, not the browser. You can find a more detailed explanation here https://github.com/sindresorhus/ama/issues/446.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
