### ISSUE TITLE
Pseudo-sync approach?

### ISSUE THREAD

**Issue by jfoclpf** [sindresorhus/is-online#46]
Beforehand I'd like to thank you for the package.

My all huge code doesn't  make any sense without Internet, thus I just exit if there is no internet.
I understand that the paradigm of nodejs is all async, but do I really need to insert all my code into the enclosure of `then` ?

I'm not that versed on promises but this approach is not working

```js
const isOnline = require('is-online');
let online = await isOnline();
console.log(online);
```
```
var online = await isOnline();
                   ^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

My node version: `v8.0.0`

Thank you

**Comment by SamVerschueren** [comment]
Support questions are better asked on StackOverflow. You can't use top-level await.

```js
const isOnline = require('is-online');

(async () => {
     const online = await isOnline();
})();
```

For further questions, see StackOverflow. This has nothing to do with this module, that's just how Node works.

**Comment by jfoclpf** [comment]
Thank you
yes, I was checking SO and realised that `await` must be called within an `async` function.
