### ISSUE TITLE
Option to disable plain http calls to Apple servers

### ISSUE THREAD

**Issue by Cediddi** [sindresorhus/is-online#50]
Plain http calls are something I very rarely do nowadays. While the call to the Apple servers is unsignificant, I still prefer not sending plain http requests to Apple at all. I'd be so happy if there were an option to disable servers. Also sending https requests to Apple would be a good improvement too.

**Comment by sindresorhus** [comment]
We're intentionally using plain HTTP for that check in case HTTPS is blocked, which happens a lot when the internet is behind some kind of captive portal. A good PR with test and docs welcome for adding this, but I'm closing this issue as it's not very important.

**Comment by working-name** [comment]
@sindresorhus I disagree. Mailspring is offline 100% of the time when it cannot get a proper response from captive.apple.com. My pihole blocks that crap, it's useless on my home network, I am my own network manager, my pi resets power to the modem when it detects an issue. Yes, I can spoof a local captive portal and return `<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>`, but that doesn't save face for Mailspring; on the contrary.

You're literally crippling your own app based on a response that is requested every so many seconds without any basis - your app did not have issues connecting and then started checking on it. This is not a smart solution to a problem, **it is the problem**.
