### ISSUE TITLE
Over Corporate Proxy 

### ISSUE THREAD

**Issue by puentesdiaz** [sindresorhus/is-online#51]
Iam behind proxy corporative.
I can use npm for install package fine using proxy corporate.

but when i run:

`is-online`

return

`Offline`

Some idea?

**Comment by silverwind** [comment]
The HTTP checks will fail because `got` does not support proxies, but if your DNS is working, you should still get a result. Try if `dig @208.67.222.222 myip.opendns.com` works.

**Comment by puentesdiaz** [comment]
> The HTTP checks will fail because `got` does not support proxies, but if your DNS is working, you should still get a result. Try if `dig @208.67.222.222 myip.opendns.com` works.

Sad. Not found

**Comment by sindresorhus** [comment]
PR welcome for a fix, but generally with corporate proxies, you're on your own.
