### ISSUE TITLE
Not supporting when npm run build

### ISSUE THREAD

**Issue by sravanshty** [sindresorhus/is-online#53]
Hello,

I  utilized in my sample application, when i start using "npm start" it is working fine. But when i try to build using "npm run build" showing error like Missing( > ) with UglifyJs. Could you please let me know how to resolve this issue.
Thanks in advance.

**Comment by sindresorhus** [comment]
It's up to you to transpile it with Babel if you want to use it in the browser. Uglify doesn't support ES2015 syntax.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by sravanshty** [comment]
Thanks @sindresorhus for your support
