### ISSUE TITLE
Make the `version` option a number instead of a string

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/is-online#59]
@silverwind Why is it a string? It feels more natural for it to be a number.

**Comment by silverwind** [comment]
No real reason, but if we want to stay consistent with `internal-ip`, `is-ip`, `is-cidr`, `ip-regex`, `cidr-regex`, it would have to be methods, e.g. `isOnline.{v4,v6}()` and `isOnline()` being a separate method that possibly checks both (thought, I'm not sure if someone with only IPv6 working can be considered online).

**Comment by sindresorhus** [comment]
Having methods for it doesn't make sense here as it's an obscure option almost no one will need.

**Comment by sindresorhus** [comment]
This is not important, so we can just make sure to change to accept a number instead in the next major version.

**Comment by sindresorhus** [comment]
I would also like to rename the option to `ipVersion` as it's not obvious when just reading it that it's for IP.

**Comment by deadcoder0904** [comment]
@sindresorhus should I make `version` a number instead of a string & send a PR as it makes sense imo?

**Comment by sindresorhus** [comment]
@deadcoder0904 Nah, the issue is here so we can do the change if we need to do another major release. It's not doing a major release just for this.
