### ISSUE TITLE
Unable to install, 404 Not Found: @szmarczak/http-timer@^1.1.2

### ISSUE THREAD

**Issue by diegoribero** [sindresorhus/is-online#62]
I was unable to test the library, unable to find that http-timer module

After running `npm install is-online`
I get that `404 Not Found: @szmarczak/http-timer@^1.1.2` error

![image](https://user-images.githubusercontent.com/11444484/59635640-4fc38600-9117-11e9-8150-f7c6cda3f01f.png)

**Comment by sindresorhus** [comment]
That's a problem with your system or npm setup. Try upgrading npm.

Support: https://npm.community/c/support
