### ISSUE TITLE
Test URL `https://ipv4.icanhazip.com/` is not working.

### ISSUE THREAD

**Issue by yashjangid1** [sindresorhus/is-online#64]
### Problem
Test URL `https://ipv4.icanhazip.com/` is not currently working. 
**Reported on** - `2019-06-24T11:01:04.450Z`
### Suggestion
I think if your server to test url is down then you should redirect request to another test url to check internet connectivity.

**Comment by silverwind** [comment]
Service is up again. Opened https://github.com/sindresorhus/public-ip/issues/32 on the correct repo.
