### ISSUE TITLE
isOnline().then giving error that it is not a function after new update 8.5.0

### ISSUE THREAD

**Issue by shubhamvyapar** [sindresorhus/is-online#77]
When the internet is not available then isOnline(...).then is giving error that isOnline(...).then is not a function. It started happening for 8.5.0. Till 8.4.0 it was working fine.

**Comment by sindresorhus** [comment]
// @Richienb

**Comment by Richienb** [comment]
@shubhamvyapar Is this on Node.js or in the browser?
