### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by Dahkenangnon** [sindresorhus/is-online#82]
Bundling main process...

 WARNING  Compiled with 3 warnings                                                                                             16:16:01
 warning  in ./node_modules/got/source/request-as-event-emitter.js

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

 warning  in ./node_modules/keyv/src/index.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/is-online/node_modules/keyv/src/index.js

Critical dependency: the request of a dependency is an expression

**Comment by sindresorhus** [comment]
It's better to ask bundling questions on the repo of the bundler you use.
