### ISSUE TITLE
How can I emulate the Offline mode?

### ISSUE THREAD

**Issue by ilko222** [sindresorhus/is-online#87]
Hello!
We are using this library on our project to check Internet connectivity.

I need to create some autotests for our App in the Offline mode w/o a real turning server to the Offline state.
I tried to set the default response timeout to 1 ms and seems it's working. But not really good for my purposes. Because we are using App build on that server and I need to restart the App all the time when I need to switch Offline/Online mode. I would like to do this "on the fly".

Is it possible?
How?

**Comment by sindresorhus** [comment]
Your best bet is probably mocking.
