### ISSUE TITLE
Use with node

### ISSUE THREAD

**Issue by efattal** [sindresorhus/is-online#95]
Hello,

I would like to use is-online in the main process of an Electron app. My code is simply this:
```
import isOnline from "is-online";

mainWindow
    .on("ready-to-show", async () => {
        setInterval(async () => {
            ipcMain.emit("online:status", await isOnline());
        }, 5000);
    })
```

But I get this error :
```
(node:14752) UnhandledPromiseRejectionWarning: ReferenceError: navigator is not defined`
```
It's like if the executed code comes from the browser.js instead of index.js. What's wrong with my implementation? Thanks for your help.

**Comment by sindresorhus** [comment]
Your bundler config is incorrect. The package correctly defines the exports for Node.js and browser: https://github.com/sindresorhus/is-online/blob/b0d113aa495c9d2746b0e7d58af74ddfbd8579ae/package.json#L17-L21

**Comment by efattal** [comment]
Thanks a lot for you answer. I saw that your exports correctly defines the target, that's why I was suprised. I'm using electron-forge+vite. Any tip about what I should check in the configuration? Thanks again for your help.

**Comment by efattal** [comment]
Actually my vite.main.config.js contains this but it is not enough. Any idea why?

```
export default defineConfig({
  resolve: {
    // Some libs that can run in both Web and Node.js, such as `axios`, we need to tell Vite to build them in Node.js.
    browserField: false,
    mainFields: ["module", "jsnext:main", "jsnext", "node"],
  },
  build: {
    rollupOptions: {
      external: nativeModules,
    },
  },
});
```

**Comment by efattal** [comment]
OK, so finally the correct configuration need the `conditions` field.
```
export default defineConfig({
  resolve: {
    // Some libs that can run in both Web and Node.js, such as `axios`, we need to tell Vite to build them in Node.js.
    browserField: false,
    mainFields: ["module", "jsnext:main", "jsnext"],
    conditions: ["node"],
  },
  build: {
    rollupOptions: {
      external: nativeModules,
    },
  },
});
```

Thanks for all the fantastic job you do. Kudos.
